name: publish package
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: "latest"
      - name: Configure GPG Key
        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Publish package
        run: cd clj-umi && lein deploy github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
